const Map<String, List<String>> indiaStatesCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Tirupati",
    "Rajahmundry",
    "Kakinada",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Vizianagaram",
    "Other"
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Ziro",
    "Tezu",
    "Bomdila",
    "Tawang",
    "Other"
  ],
  "Assam": [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Karimganj",
    "Sibsagar",
    "Other"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Other"
  ],
  "Chhattisgarh": [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Other"
  ],
  "Goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Other"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Nadiad",
    "Morbi",
    "Mehsana",
    "Bharuch",
    "Vapi",
    "Valsad",
    "Navsari",
    "Bhuj",
    "Porbandar",
    "Other"
  ],
  "Haryana": [
    "Faridabad",
    "Gurugram (Gurgaon)",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Sirsa",
    "Other"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Nahan",
    "Hamirpur",
    "Una",
    "Kullu",
    "Other"
  ],
  "Jharkhand": [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Other"
  ],
  "Karnataka": [
    "Bengaluru (Bangalore)",
    "Mysuru (Mysore)",
    "Hubballi-Dharwad",
    "Mangaluru (Mangalore)",
    "Belagavi (Belgaum)",
    "Davanagere",
    "Ballari (Bellary)",
    "Kalaburagi (Gulbarga)",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Udupi",
    "Other"
  ],
  "Kerala": [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Palakkad",
    "Kannur",
    "Kottayam",
    "Manjeri",
    "Other"
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Singrauli",
    "Other"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Pimpri-Chinchwad",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad",
    "Navi Mumbai",
    "Solapur",
    "Mira-Bhayandar",
    "Amravati",
    "Nanded",
    "Kolhapur",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Other"
  ],
  "Manipur": [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Senapati",
    "Other"
  ],
  "Meghalaya": [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Jowai",
    "Baghmara",
    "Other"
  ],
  "Mizoram": [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Other"
  ],
  "Nagaland": [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Other"
  ],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Other"
  ],
  "Punjab": [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Sahibzada Ajit Singh Nagar (Mohali)",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Abohar",
    "Other"
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Sri Ganganagar",
    "Pali",
    "Other"
  ],
  "Sikkim": [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan",
    "Other"
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli (Trichy)",
    "Salem",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Tirunelveli",
    "Nagercoil",
    "Thanjavur",
    "Dindigul",
    "Other"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Other"
  ],
  "Tripura": [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Kailasahar",
    "Belonia",
    "Other"
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Prayagraj (Allahabad)",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Ayodhya",
    "Other"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Haldwani",
    "Roorkee",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Other"
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Darjeeling",
    "Siliguri",
    "Asansol",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Kharagpur",
    "Haldia",
    "Kalyani",
    "Other"
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Other"
  ],
  "Chandigarh": [
    "Chandigarh",
    "Other"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Other"
  ],
  "Delhi": [
    "New Delhi",
    "Delhi",
    "Dwarka",
    "Rohini",
    "Narela",
    "Other"
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Kathua",
    "Sopore",
    "Other"
  ],
  "Ladakh": [
    "Leh",
    "Kargil",
    "Other"
  ],
  "Lakshadweep": [
    "Kavaratti",
    "Minicoy",
    "Amini",
    "Other"
  ],
  "Puducherry": [
    "Puducherry",
    "Karaikal",
    "Yanam",
    "Mahe",
    "Other"
  ]
};
